### ISSUE TITLE
Relative Memory configuration - -XX:MaxDirectMemorySize

### ISSUE THREAD

**Issue by hirik** [yajsw/yajsw#6]
Is there any way to set java directmemorysize in relative percentage like heap size?

**Comment by hirik** [comment]
@rzorzorzo , Is there any workaround available to configure this?

**Comment by rzorzorzo** [comment]
hello,
currently not implemented 
but since you can use groovy in the conf file maybe you could try something like: 

create a file scripts/relativeRAM.gv

> import org.rzo.yajsw.os.OperatingSystem
>
>public long calc(long val)
>{
 >     return {(OperatingSystem.instance().systemInformation().totalRAM()/100)* value as Long
>}

and use it in the conf file:

> wrapper.config.script.relativeRAM= scripts/relativeRAM.gv
> wrapper.java.additional.1 = -XX:MaxDirectMemorySize=${relativeRAM.invoke('calc', 15 as Long)}

i havnt tried it out so let me know if this works.

-- Ron

**Comment by hirik** [comment]
Hi @rzorzorzo ,

I'm getting this exception 
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.rzo.yajsw.boot.WrapperExeBooter.main(WrapperExeBooter.java:49)
Caused by: java.lang.StringIndexOutOfBoundsException: begin 26, end -1, length 51
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3410)
        at java.base/java.lang.String.substring(String.java:1883)
        at org.rzo.yajsw.config.groovy.GInterpolator.interpolate(GInterpolator.java:76)
        at org.apache.commons.configuration2.convert.DefaultConversionHandler.extractConversionValue(DefaultConversionHandler.java:282)
        at org.apache.commons.configuration2.convert.DefaultConversionHandler.convert(DefaultConversionHandler.java:234)
        at org.apache.commons.configuration2.convert.DefaultConversionHandler.to(DefaultConversionHandler.java:116)
        at org.apache.commons.configuration2.AbstractConfiguration.getAndConvertProperty(AbstractConfiguration.java:1763)
        at org.apache.commons.configuration2.AbstractConfiguration.convert(AbstractConfiguration.java:1795)
        at org.apache.commons.configuration2.AbstractConfiguration.getString(AbstractConfiguration.java:1354)
        at org.rzo.yajsw.config.YajswConfigurationImpl.getString(YajswConfigurationImpl.java:656)
        at org.rzo.yajsw.wrapper.WrappedJavaProcess.jvmOptions(WrappedJavaProcess.java:263)
        at org.rzo.yajsw.wrapper.WrappedJavaProcess.configProcess(WrappedJavaProcess.java:141)
        at org.rzo.yajsw.wrapper.AbstractWrappedProcess.startInternal(AbstractWrappedProcess.java:1281)
        at org.rzo.yajsw.wrapper.AbstractWrappedProcess.start(AbstractWrappedProcess.java:1154)
        at org.rzo.yajsw.wrapper.WrappedProcessList.startAll(WrappedProcessList.java:26)
        at org.rzo.yajsw.WrapperExe.doConsole(WrapperExe.java:641)
        at org.rzo.yajsw.WrapperExe.executeCommand(WrapperExe.java:156)
        at org.rzo.yajsw.WrapperExe.main(WrapperExe.java:124)
```

**Comment by hirik** [comment]
My conf entries 

wrapper.config.script.relativeRAM=${server.home}/scripts/relativeRAM.gv
wrapper.java.additional.4.6=-XX:MaxDirectMemorySize=${relativeRAM.invoke('calc', 25)}

**Comment by rzorzorzo** [comment]
hi,

there are 2 bugs:
>public long calc(long val) -> public long calc(long value)

> wrapper.java.additional.4.6=-XX:MaxDirectMemorySize=${relativeRAM.invoke('calc', 25)} -> wrapper.java.additional.4.6=-XX:MaxDirectMemorySize=${relativeRAM.invoke('calc'\\, 25)}

that is:
"," should be escaped
method arg should be value

-- Ron

**Comment by hirik** [comment]
@rzorzorzo,  Now it's working. 

The problem was ",".  Thanks for this wonderful library 👍 .
